---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  production.json: |
    {
      "log": {
        "level": "{{ .Values.logLevel }}"
      },
      "tls": {
        "enabled": true
      }
    }