apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-jacoco-operator.fullname" . }}
  labels:
    {{- include "k8s-jacoco-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-jacoco-operator.selectorLabels" . | nindent 4 }}
